[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'rhowardiv/nginx-vim-syntax'

[[plugins]]
repo = 'moll/vim-node'

[[plugins]]
repo = 'bfontaine/Brewfile.vim'

[[plugins]]
repo = 'vim-scripts/logstash.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'plytophogy/vim-virtualenv'

[[plugins]]
repo = 'PieterjanMontens/vim-pipenv'

[[plugins]]
# repo = 'bling/vim-airline'
repo = 'itchyny/lightline.vim'

# [[plugins]]
# repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'fuadsaud/vim-react-snippets'

[[plugins]]
repo = 'pgilad/vim-react-proptypes-snippets'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-line'
depends = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-indent'
depends = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-entire'
depends = 'kana/vim-textobj-user'

[[plugins]]
repo = 'PeterRincker/vim-argumentative'

[[plugins]]
repo = 'junegunn/vim-slash'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tpope/vim-fugitive'
augroup = 'fugitive'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
