[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'
on_ft = 'vim'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

# [[plugins]]
# repo = 'StanAngeloff/php.vim'
# on_ft = 'php'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'
on_ft = ['jinja2', 'j2', 'jinja']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'wting/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'ap/vim-css-color'
on_ft = ['css','scss','sass','less','styl']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'less']

[[plugins]]
repo = 'ingydotnet/yaml-vim'
on_ft = ['yml', 'yaml']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['sass', 'scss']

[[plugins]]
repo = 'wavded/vim-stylus'
on_ft = 'stylus'

[[plugins]]
repo = 'groenewege/vim-less'
on_ft = ['less', 'css']

[[plugins]]
repo = 'csscomb/vim-csscomb'
on_ft = ['css', 'less', 'sass']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = 'html'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['jade', 'pug']

[[plugins]]
repo = 'gregsexton/MatchTag'
on_ft = ['html','xml']

[[plugins]]
repo = 'othree/xml.vim'
on_ft = 'xml'

[[plugins]]
repo = 'darfink/vim-plist'
on_ft = 'plist'

[[plugins]]
repo = 'samuelsimoes/vim-jsx-utils'
on_ft = 'javascript'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'

[[plugins]]
repo = 'itspriddle/vim-jquery.git'
on_ft = 'javascript'

[[plugins]]
repo = 'heavenshell/vim-jsdoc'
on_ft = 'javascript'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'coffee']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'waylan/vim-markdown-extra-preview'
on_ft = 'markdown'

[[plugins]]
repo = 'jtratner/vim-flavored-markdown.git'
on_ft = 'markdown'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'gorkunov/smartgf.vim'
on_map = '<Plug>(smartgf-search'
disabled = "!executable('ag')"

[[plugins]]
repo = 'AndrewRadev/linediff.vim'
on_cmd = ['Linediff', 'LinediffReset']

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin', 'kt']
